#!/usr/bin/env python
# -*- coding: utf-8 -*-
##########################################################################
# ./import - Import IP/MAC bindings from distant phpipam server
# Copyright © 2014 Ghislain Loaec <gloaec@cadoles.com>
#
# License GPLv3: http://sourceforge.net/directory/license:gplv3/
##########################################################################

from phpipam import Api

if __name__ == "__main__":
    config = {}
    execfile("phpipam.conf", config)

    api = Api(app_id=config['APP_ID'], 
              app_key=config['APP_KEY'], 
              api_url=config['API_URL'])
    
    print "==[export.csv]================================================="
    print api.exportAddresses(format='csv')
    
    print "==[/etc/dhcp3/dhcpd.conf]======================================"
    print api.exportAddresses(format='dhcpd.conf')
